coq_version           = 8.4
coq_dir              := coq-$(coq_version)
# coq_tarfile         = coq-$(coq_version).tar.gz
# coq_fetch           = $(call wget,coq,http://coq.inria.fr/distri/$(coq_tarfile))
# coq_extract         = $(call untar-z,coq,$(coq_tarfile))
# coq_build           = $(call make,coq,PREFIX=$(call install_dir,coq))
coq_install         = false
$(call requires,coq,lablgtk ocaml)
$(eval $(call package,coq))
# Local Variables:
# compile-command: "make -C .. build-coq"
# End:
