with_version = 1
with_dir = ..
with_install =	mkdir -p $(call install_dir,with)/bin && \
		sed -e 's\#@TOPDIR@\#$(topdir)\#g' \
		    -e 's\#@ENCAP_SER_NO@\#$(ENCAP_SER_NO)\#g' \
			<with/with.sh \
			>$(call install_dir,with)/bin/with && \
		chmod a+x $(call install_dir,with)/bin/with
$(call files_dir,with)/.made-install: with/with.sh with/Makefile.include
$(call requires,with)
$(eval $(call package,with))
# Local Variables:
# compile-command: "make -C .. linkup-with"
# End:
